function modelName = build_simulink_replay_model()
%BUILD_SIMULINK_REPLAY_MODEL Create and save the NARX replay validation model.

cfg = project_config();
prepare_simulink_replay();

targetDir = fullfile(cfg.rootDir, "simulink", "narx");
targetFile = fullfile(targetDir, "narx_replay_validation.slx");
if ~isfolder(targetDir)
    mkdir(targetDir);
end
assert(~isfile(targetFile), ...
    "Target already exists. Move or rename it before rebuilding: %s", targetFile);

% Reuse the model currently produced by gensim when possible.
generatedModel = "untitled";
if ~bdIsLoaded(generatedModel)
    generatedModel = string(gensim(evalin("base", "netClosed"), 1));
end

topSubsystems = find_system(generatedModel, "SearchDepth", 1, ...
    "BlockType", "SubSystem");
controllerBlock = "";
for k = 1:numel(topSubsystems)
    if contains(string(get_param(topSubsystems{k}, "Name")), "NARX", ...
            "IgnoreCase", true)
        controllerBlock = string(topSubsystems{k});
        break;
    end
end
assert(strlength(controllerBlock) > 0, ...
    "Could not find the generated NARX subsystem in %s.", generatedModel);

% Remove gensim's example source/sink and existing top-level lines.
existingLines = find_system(generatedModel, "FindAll", "on", ...
    "SearchDepth", 1, "Type", "line");
for k = 1:numel(existingLines)
    delete_line(existingLines(k));
end

topBlocks = find_system(generatedModel, "SearchDepth", 1, "Type", "Block");
for k = 1:numel(topBlocks)
    blockPath = string(topBlocks{k});
    if blockPath ~= string(generatedModel) && blockPath ~= controllerBlock
        delete_block(blockPath);
    end
end

set_param(controllerBlock, "Position", [330 145 500 245]);
set_param(controllerBlock, "Name", "NARX Controller");
controllerBlock = generatedModel + "/NARX Controller";

add_block("simulink/Sources/From Workspace", ...
    generatedModel + "/Recorded NARX Inputs", ...
    "VariableName", "narxReplayInput", ...
    "Position", [55 145 200 185]);
add_block("simulink/Sources/From Workspace", ...
    generatedModel + "/Recorded PI Target", ...
    "VariableName", "piReplayTarget", ...
    "Position", [55 300 200 340]);
add_block("simulink/Signal Routing/Mux", ...
    generatedModel + "/Compare Outputs", ...
    "Inputs", "2", "Position", [625 145 630 255]);
add_block("simulink/Sinks/Scope", generatedModel + "/Output Scope", ...
    "Position", [700 175 750 225]);
add_block("simulink/Math Operations/Sum", ...
    generatedModel + "/Replay Error", ...
    "Inputs", "+-", "Position", [600 315 625 345]);

add_block("simulink/Sinks/To Workspace", ...
    generatedModel + "/Save NARX Output", ...
    "VariableName", "simNarxOutput", "SaveFormat", "Timeseries", ...
    "Position", [700 75 825 105]);
add_block("simulink/Sinks/To Workspace", ...
    generatedModel + "/Save PI Target", ...
    "VariableName", "simPiTarget", "SaveFormat", "Timeseries", ...
    "Position", [700 285 825 315]);
add_block("simulink/Sinks/To Workspace", ...
    generatedModel + "/Save Replay Error", ...
    "VariableName", "simReplayError", "SaveFormat", "Timeseries", ...
    "Position", [700 365 825 395]);

add_line(generatedModel, "Recorded NARX Inputs/1", "NARX Controller/1", ...
    "autorouting", "on");
add_line(generatedModel, "NARX Controller/1", "Compare Outputs/1", ...
    "autorouting", "on");
add_line(generatedModel, "Recorded PI Target/1", "Compare Outputs/2", ...
    "autorouting", "on");
add_line(generatedModel, "Compare Outputs/1", "Output Scope/1", ...
    "autorouting", "on");
add_line(generatedModel, "NARX Controller/1", "Save NARX Output/1", ...
    "autorouting", "on");
add_line(generatedModel, "Recorded PI Target/1", "Save PI Target/1", ...
    "autorouting", "on");
add_line(generatedModel, "Recorded PI Target/1", "Replay Error/1", ...
    "autorouting", "on");
add_line(generatedModel, "NARX Controller/1", "Replay Error/2", ...
    "autorouting", "on");
add_line(generatedModel, "Replay Error/1", "Save Replay Error/1", ...
    "autorouting", "on");

sampleCount = numel(evalin("base", "piReplayTarget.signals.values"));
set_param(generatedModel, "SolverType", "Fixed-step", ...
    "Solver", "FixedStepDiscrete", "FixedStep", "1", ...
    "StartTime", "0", "StopTime", string(sampleCount - 1));

save_system(generatedModel, targetFile);
open_system(targetFile);
modelName = "narx_replay_validation";
fprintf("Saved replay model to %s\n", targetFile);
fprintf("Run the model, then inspect simNarxOutput, simPiTarget, and simReplayError.\n");
end
